### ISSUE TITLE
issue: Can't set up project, can't run the demo

### ISSUE THREAD

**Issue by LiShuxue** [esp/esp-js#232]
## issue 1, error in terminal console
reproduce step
1. git clone the project
2. "cd" to the root path, and run " lerna bootstrap "
3. then , i try to run the "agile board" demo, so i excute "lerna run start" in terminal

result
![image](https://user-images.githubusercontent.com/20234214/68098770-a4ff0900-fef9-11e9-89da-1868da11059f.png)

## issue 2, error in browser console
because the above behaviour has error, so i try to go to "agile-board" demo path to do something, so i do below
1. cd to "esp-js-react-agile-board" path
2. yarn install
3. yarn start

now every thing  looks fine in terminal console, so i try to open "localhost:4000" in Chrome browser 78.0.3904.70. it just show a blank page, and seems there have some error in console
![image](https://user-images.githubusercontent.com/20234214/68098931-877e6f00-fefa-11e9-98fa-282bb67dbeb3.png)

Do you have any idea about that ?

**Comment by LiShuxue** [comment]
Another question:
<b>What the difference or advantage compare with React-Redux ?</b>

I mean, you know, the Redux can dispatch some action , and change the store state, then the view will change.

and seems ESP-JS are doing same thing, ESP-js seems use the publish-subscribe pattern, publish the event to eventHub, and eventHub trigger the event to change the modal state, then the view be changed. am i right ?

Could you help me clarify that ? Thank you !

**Comment by KeithWoods** [comment]
Thanks for taking the time to report the issue with the examples. I've just pushed #233 to fix. They should all run now.

Regarding your second question, I answered a bit on gitter but will paste here for the record :)

Regarding your other question. You're right esp is conceptually similar to redux. The router in esp-js, which is the core component in the pattern, is (as it turned out) an implementation of the uni directional state management flow. That is, you publish an event, the router give it to a model to process, that processing is up to the developer to implement (though other esp libs can be used to help there), then when teh event is processed the router pushes it to anything observing the model. Typically observers are views.

esp started as esp-js when redux wasn't around, it was actually used via c# first, then over the years it's evolved along with front end tech (movement from wpf, to silverlight to web).

Today, there are additional libraries in esp that allow you to build composite applications where multiple models (equivalent to stores in redux), can be implemented differently and still interop via the router. In a large complex application, there may be 100+ different models providing different APIs or functionality and they can all co exist in one application and be developed independently
I've only recently merged the esp 2.0 release into the master branch, so I have some left over work, specifically updating the documentation.

If I had to compare it to other offerings, it takes the view layer from React, the modular application concepts that exist in other frameworks like angular (and many predecessors before), and state management which is more inline with uni directional patterns. It's largely suited to real time SPA. It's been predominately used in push based financial systems.

Most of those points are largely independent, what's of most concern to developers is what state manipulation code is written in as that's where 90% of your app will be. The core esp-js package doesn't dictate how you mutate your state, it just tells you that you need to (in response to something publishing an event). A lot of earlier state manipulation models were implemented in OO which is great for all the OO reasons, but not so great in the React world as at generally favours immutable objects. In short due to poor equality handling in the language and it's much easier to do instance equality which doesn't work well with OO in JS. Of course there are other benefits and pros and cons, it's a holy war :). Over time models have become much more akin to the redux pattern via esp-js-polimer (for example this view implementation here https://github.com/esp/esp-js/tree/master/examples/esp-js-ui-module-based-app/src/trading-module/cash-tile/model). On the road map is to add a shim so models can be done via React hooks which will effectively mean esp can be used for the composite application aspects (the 10% of your code) and you model hour state using pure JS and React (the 90%).

Apologies for the readme being behind the code base. release 2.0 is stable, been using it for over a year on. I've just wanted to let it settle before updating the docs. Hopefully that'll happen before the the new year.
